### ISSUE TITLE
Getting error: signal SIGSEGV: segmentation violation

### ISSUE THREAD

**Issue by Lucas-C** [juliensalinas/torrengo#6]
Just wanted to report this failure:
```
# torrengo Bruges
...
Please select a torrent to download (enter its index):
0
Do you want to open torrent in Deluge client? [y / n]
n
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x60bd12]

goroutine 1 [running]:
net/http.(*Client).deadline(0x0, 0xffffffffffffffff, 0x203000, 0xb90000c0006baf38)
        /usr/local/go/src/net/http/client.go:187 +0x22
net/http.(*Client).do(0x0, 0xc000156300, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:527 +0x22c
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:509
github.com/juliensalinas/torrengo/core.Fetch(0xc00069e200, 0x76, 0x0, 0x0, 0x0, 0xc00069e207)
        /root/gocode/src/github.com/juliensalinas/torrengo/core/core.go:39 +0x543
github.com/juliensalinas/torrengo/td.DlFile(0xc00069e200, 0x76, 0x12a05f200, 0x0, 0x0, 0x0, 0x0)
        /root/gocode/src/github.com/juliensalinas/torrengo/td/download.go:69 +0x270
main.getTorrentFile(0x0, 0x0, 0x0, 0x0, 0x12a05f200, 0x0)
        /root/gocode/src/github.com/juliensalinas/torrengo/torrengo.go:155 +0x7fe
main.main()
        /root/gocode/src/github.com/juliensalinas/torrengo/torrengo.go:655 +0x20de
```

**Comment by juliensalinas** [comment]
Thanks for the feedback @Lucas-C.
Actually the TorrentDownloads site (td above) has always been pretty buggy and is not even working at all today so I think I'll drop the support...
But in any case the error above also shows that I did not handle this error gracefully so thanks again for the feedback.
